from enum import Enum

class CaseState(str, Enum):
    OPEN = "OPEN"
    ANALYZING = "ANALYZING"
    ACTION_READY = "ACTION_READY"
    PENDING_RECOVERY = "PENDING_RECOVERY"
    WAITING_PAYMENT = "WAITING_PAYMENT"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    STOPPED = "STOPPED"

class PTPStatus(str, Enum):
    ACTIVE = "ACTIVE"
    KEPT = "KEPT"
    BROKEN = "BROKEN"
    EXPIRED = "EXPIRED"

class FailureReason(str, Enum):
    INCORRECT_PIN = "incorrect_pin"
    AUTHENTICATION_FAILED = "authentication_failed"
    INSUFFICIENT_FUNDS = "insufficient_funds"
    BALANCE_LOW = "balance_low"
    CARD_EXPIRED = "card_expired"
    BANK_DECLINED = "bank_declined"
    BANK_DOWN = "bank_down"
    GATEWAY_TIMEOUT = "gateway_timeout"
    NETWORK_ERROR = "network_error"
    PAYMENT_METHOD_UNAVAILABLE = "payment_method_unavailable"
    CUSTOMER_CANCELLED = "customer_cancelled"
    RISK_DECLINED = "risk_declined"
    FRAUD_SUSPECTED = "fraud_suspected"
    UNKNOWN = "unknown"

class FailureCategory(str, Enum):
    CUSTOMER_CORRECTABLE = "CUSTOMER_CORRECTABLE"
    TEMPORARY_INFRASTRUCTURE = "TEMPORARY_INFRASTRUCTURE"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    PAYMENT_METHOD_PROBLEM = "PAYMENT_METHOD_PROBLEM"
    CUSTOMER_ABANDONMENT = "CUSTOMER_ABANDONMENT"
    RISK_RELATED = "RISK_RELATED"
    UNKNOWN = "UNKNOWN"

class RecoveryChannel(str, Enum):
    EMAIL = "EMAIL"
    WHATSAPP = "WHATSAPP"
    VOICE = "VOICE"

class RecoveryActionType(str, Enum):
    SEND_PAYMENT_LINK = "SEND_PAYMENT_LINK"
    WAIT_AND_RETRY = "WAIT_AND_RETRY"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    DO_NOT_RETRY = "DO_NOT_RETRY"
    CREATE_PROMISE_TO_PAY = "CREATE_PROMISE_TO_PAY"

class PolicyResult(str, Enum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    DELAY = "DELAY"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class FraudAlertType(str, Enum):
    REFUND_ABUSE = "REFUND_ABUSE"
    DUPLICATE_REFUND = "DUPLICATE_REFUND"
    REFUND_SPIKE = "REFUND_SPIKE"
    UNUSUAL_BEHAVIOR = "UNUSUAL_BEHAVIOR"
    HIGH_RISK_CUSTOMER = "HIGH_RISK_CUSTOMER"

class FraudSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class FraudAlertStatus(str, Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    RESOLVED = "RESOLVED"
    DISMISSED = "DISMISSED"

class AuditEventType(str, Enum):
    PAYMENT_FAILURE_RECEIVED = "PAYMENT_FAILURE_RECEIVED"
    CASE_CREATED = "CASE_CREATED"
    FAILURE_CLASSIFIED = "FAILURE_CLASSIFIED"
    ML_SCORING_STARTED = "ML_SCORING_STARTED"
    ML_SCORE_GENERATED = "ML_SCORE_GENERATED"
    ERV_CALCULATED = "ERV_CALCULATED"
    CHANNEL_RECOMMENDED = "CHANNEL_RECOMMENDED"
    ML_SCORING_FAILED = "ML_SCORING_FAILED"
    CHARGEBACK_PREDICTED = "CHARGEBACK_PREDICTED"
    FRAUD_ALERT_GENERATED = "FRAUD_ALERT_GENERATED"
    FRAUD_ALERT_RESOLVED = "FRAUD_ALERT_RESOLVED"
    COPILOT_QUERY_PROCESSED = "COPILOT_QUERY_PROCESSED"
    REFUND_TRIGGERED = "REFUND_TRIGGERED"
    AI_RECOMMENDATION_CREATED = "AI_RECOMMENDATION_CREATED"
    POLICY_ALLOWED = "POLICY_ALLOWED"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    MANUAL_REVIEW_REQUESTED = "MANUAL_REVIEW_REQUESTED"
    MANUAL_APPROVED = "MANUAL_APPROVED"
    MANUAL_REJECTED = "MANUAL_REJECTED"
    PAYMENT_LINK_CREATED = "PAYMENT_LINK_CREATED"
    RECOVERY_MESSAGE_SENT = "RECOVERY_MESSAGE_SENT"
    PROMISE_TO_PAY_CREATED = "PROMISE_TO_PAY_CREATED"
    PAYMENT_CAPTURED = "PAYMENT_CAPTURED"
    REVENUE_RECOVERED = "REVENUE_RECOVERED"
    RECOVERY_STOPPED = "RECOVERY_STOPPED"
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
    WEBHOOK_REJECTED = "WEBHOOK_REJECTED"
